process_manager:
  port: 50055

# ===== LOG COLLECTION CONFIGURATION (OPTIONAL) =====
log_collection:
  enabled: true
  global_aggregation:
    enabled: true
    targets:
      - type: "process_manager_stdout"
        format: "enhanced_plain"
        prefix: "[AGGREGATED]"
      - type: "file" 
        path: "process_manager-aggregated.log"
        format: "enhanced_plain"
  default:
    enabled: true
    capture_stdout: true
    capture_stderr: true
    outputs:
      separate:
        stdout:
          - type: "file"
            path: "{process_id}-stdout.log"
            format: "enhanced_plain"
        stderr:
          - type: "file"
            path: "{process_id}-stderr.log"
            format: "enhanced_plain"
          - type: "process_manager_stdout"
            format: "enhanced_plain"
            prefix: "[ERROR]"

managed_processes:
  - id: "test-managed-1"
    type: "standard_managed"
    profile_type: "web"  # ✅ NEW: Echo gRPC server is a web service
    unit:
      standard_managed:
        metadata:
          name: "Echo gRPC server with logging"
        control:
          execution:
            executable_path: "..\\..\\..\\..\\hsu-example1-go\\cmd\\srv\\echogrpcsrv\\echogrpcsrv.exe"
            args: ["--port", "50051"]
          restart_policy: "on-failure"  # ✅ NEW: Separated restart policy
          context_aware_restart:        # ✅ NEW: Context-aware restart configuration
            default:
              max_retries: 3
              retry_delay: "5s"
              backoff_rate: 1.5
          # ===== PROCESS-SPECIFIC LOG COLLECTION (OPTIONAL) =====
          log_collection:
            enabled: true
            outputs:
              separate:
                stdout:
                  - type: "file"
                    path: "{process_id}-detailed.log"
                    format: "enhanced_plain"
        health_check:
          type: "process"
          run_options:
            enabled: true
            interval: "10s"
            timeout: "5s"
            initial_delay: "2s"
            retries: 2
  
  - id: "test-managed-2"
    type: "standard_managed"
    profile_type: "web"  # ✅ NEW: Echo gRPC server is a web service
    unit:
      standard_managed:
        metadata:
          name: "Echo gRPC server with default logging"
        control:
          execution:
            executable_path: "..\\..\\..\\..\\hsu-example1-go\\cmd\\srv\\echogrpcsrv\\echogrpcsrv.exe"
            args: ["--port", "50052"]
          restart_policy: "on-failure"  # ✅ NEW: Separated restart policy
          context_aware_restart:        # ✅ NEW: Context-aware restart configuration
            default:
              max_retries: 3
              retry_delay: "5s"
              backoff_rate: 1.5
          # No log_collection section = uses defaults
        health_check:
          type: "process"
          run_options:
            enabled: true
            interval: "10s"
            timeout: "5s"
            initial_delay: "2s"
            retries: 2 